[project]
name = "word2vev-toy-app"
version = "0.1.0"
description = "none"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=4.44.1",
    "polars>=1.1.0",
    "gensim==4.3.3",
]

[tool.ruff]
line-length = 88

[dependency-groups]
dev = [
    "ruff>=0.8.0",
]
